# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rosette
email: julien.aldon@epitech.com
description: >- # this means to ignore newlines until "baseurl:"
  Rosette est un restaurant de cuisine francaise en plein coeur de Clichy,
  découvrez son menu de saison composé et sourcé avec amour et ses plus de 250 références de vins.
url: https://julienaldon.github.io
instagram_url: https://instagram.com
facebook_url: https://facebook.com

forme_juridique: "Société à responsabilité limitée"
capital_social: "5 000,00 €"
adresse: "77 RUE DE PARIS 92110 CLICHY"
immatriculation: "921460770"
mail: "contact@rosette-restaurant.fr"
telephone: "01.47.72.67.51"
identification_tva: "FR80921460770"
hebergeur: "Github Pages"
google_structured_data: |
    <script type="application/ld+json">
    {
      "@context": "https://schema.org/",
      "@type": "Restaurant",
      "address": {
        "@type": "PostalAdress"
        "addressLocality": "Paris",
        "addressCountry": "FR",
        "postalCode": "92110",
        "streetAddress": "77 Rue de Paris, 92110 Clichy"
      },
      "email": "contact@rosette-restaurant.fr",
      "name": "Rosette",
      "legalname": "Rosette",
      "description": "Rosette est un restaurant francais en plein coeur de Clichy, découvrez son menu de saison composé et sourcé avec amour et ses nombreuses références de vins recherchés spécialement pour vous.",
      "currenciesAccepted": "EUR",
      "priceRange": "$$",
      "openingHours": [
        "Mo 12:00-14:00",
        "Mo 19:00-20:00",
        "Tu 12:00-14:00",
        "Tu 19:00-20:00",
        "Th 12:00-14:00",
        "Th 19:00-20:00",
        "We 12:00-14:00",
        "We 19:00-20:00",
        "Fr 12:00-14:00",
        "Fr 19:00-20:00",
        "Sa 12:00-14:00",
        "Sa 19:00-20:00"
      ],
      "servesCuisine":"Francaise",
      "paymentAccepted": "Cartes de paiement, Chèques Déjeuner, Chèques, Ticket Restaurant, Carte de crédit",
      "logo": "https://www.rosette-restaurant.fr/favicon.ico"
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "48.90054612766114",
        "longitude": "2.304050777189373",
      },
      "image": "",
      "url": "https://www.rosette-restaurant.fr",
      "menu": "https://www.rosette-restaurant.fr#menu"
    }
    </script>


theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
